### PR TITLE
Update discussion and social media links

### PR DESCRIPTION
**Pull request by kevinbowrin**
Per https://fosstodon.org/@beeware/110053388972910487, here's a small PR to replace the Twitter links to Mastodon links. I used the "url as part of the link" style instead of the "url in the footnote" style. 

## PR Checklist:

- [x] All new features have been tested
- [x] All new features have been documented
- [x] I have read the **CONTRIBUTING.md** file
- [x] I will abide by the code of conduct

### CODE REVIEW

**Review by freakboy3742 — APPROVED** [review]
Thanks for the contribution!

**Review by freakboy3742 — CHANGES_REQUESTED** [review]
Ah - I've just noticed the CI failure - this is due to missing a changes file. If you add a file named `changes/90.misc.rst` that says "Twitter links updated to Mastodon", that test will pass.

Since you need to make another pass - it would also be helpful if you could update the Gitter link (which should be a link to Discord), and add a link for the Discussions forum (which exists, but isn't linked in either file you've updated).

**Comment by kevinbowrin** [comment]
> update the Gitter link (which should be a link to Discord), and add a link for the Discussions forum (which exists, but isn't linked in either file you've updated).

Done! I've also reformatted the links to use separate target definitions.

**Review by freakboy3742 — APPROVED** [review]
Awesome - thanks for the contribution!

**Pull request merged**
